version: "3.8"

services:
  mysqlcontainer:
    container_name: mysqlcontainer
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: RootPass
      MYSQL_DATABASE: apiexplorer
    ports:
      - 3307:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - networkmysql

  apicontainer:
    container_name: apicontainer
    build:
      dockerfile: Dockerfile
    ports:
      - 8090:8080
    depends_on:
      - mysqlcontainer
    environment:
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://mysqlcontainer:3306/apiexplorer
      - spring.datasource.username=root
      - spring.datasource.password=RootPass
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - logging.level.org.hibernate.SQL=DEBUG
      - logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
    networks:
      - networkmysql
    restart: on-failure

networks:
  networkmysql:
    driver: bridge


